version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subtracker-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - POSTGRES_DSN=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - APP_PORT=${APP_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15-alpine
    container_name: subtracker-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: subtracker-swagger-ui
    ports:
      - "${SWAGGER_PORT}:8080"
    environment:
      - URL=http://localhost:${APP_PORT}/swagger.json
    depends_on:
      - app
    restart: always

volumes:
  pgdata: